"""upgarde game model

Revision ID: c95e58ed13da
Revises: d4676b923f0d
Create Date: 2021-04-16 18:59:06.165913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95e58ed13da'
down_revision = 'd4676b923f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('rawg_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'rawg_id')
    # ### end Alembic commands ###
