export const GET_ALL_POSTS="GET_ALL_POSTS" 
export const GET_POST_BY_ID="GET_POST_BY_ID"
export const UPDATE_POST="UPDATE_POST"
export const CREATE_POST="CREATE_POST"
export const DELETE_POST="DELETE_POST"
export const HANDLE_POST="HANDLE_POST"

export const GET_GAMES="GET_GAMES"
export const GET_ONE_GAME="GET_ONE_GAME"
export const GET_ALL_GAME_BLOGS='GET_ALL_GAME_BLOGS'

export const SET_CURRENT_USER='SET_CURRENT_USER'
export const SET_SELECTED_USER='SET_SELECTED_USER'
export const SET_AUTHENTICATED= 'SET_AUTHENTICATED'

export const SIGNUP_FORM='SIGNUP_FORM'
export const SIGNUP_SUBMIT= 'SIGNUP_SUBMIT'

export const LOGIN_FORM='LOGIN_FORM'
export const RESET_LOGIN='RESET_FORM'

export const SEARCH_GAME="SEARCH_GAME"
export const CREATE_GAME='CREATE_GAME'
export const GET_GAME_BLOG="GET_GAME_BLOG"
